"""Schema Table Added 

Revision ID: 18332303eb87
Revises: 
Create Date: 2025-12-17 14:56:10.357142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18332303eb87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('account_status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('device_token', sa.Text(), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.CheckConstraint("account_status IN ('active', 'suspended', 'deleted', 'pending')", name='ck_users_account_status'),
    sa.CheckConstraint("gender IN ('Male', 'Female', 'Other', 'Prefer not to say')", name='ck_users_gender'),
    sa.CheckConstraint("user_type IN ('tenant', 'host', 'both')", name='ck_users_user_type'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('idx_users_account_status', 'users', ['account_status'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_users_user_type', 'users', ['user_type'], unique=False)
    op.create_table('host_preferences',
    sa.Column('preference_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('prefer_non_drinker', sa.Boolean(), nullable=False),
    sa.Column('prefer_non_smoker', sa.Boolean(), nullable=False),
    sa.Column('prefer_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('prefer_working_professional', sa.Boolean(), nullable=False),
    sa.Column('prefer_student', sa.Boolean(), nullable=False),
    sa.Column('preferred_gender', sa.String(length=20), nullable=True),
    sa.Column('preferred_age_min', sa.Integer(), nullable=True),
    sa.Column('preferred_age_max', sa.Integer(), nullable=True),
    sa.Column('other_preferences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('host_id')
    )
    op.create_table('host_profiles',
    sa.Column('host_profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('host_category', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_registration_number', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('response_time_expectation', sa.String(length=50), nullable=True),
    sa.Column('preferred_tenant_types', sa.Text(), nullable=True),
    sa.Column('avg_rating', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('total_ratings', sa.Integer(), nullable=False),
    sa.Column('total_properties_listed', sa.Integer(), nullable=False),
    sa.Column('successful_matches', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("host_category IN ('owner', 'broker', 'company', 'future_room_partner', 'flatmate', 'known_of_flatmate', 'known_of_owner')", name='ck_host_category'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('host_profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_host_profile_category', 'host_profiles', ['host_category'], unique=False)
    op.create_index('idx_host_profile_user_id', 'host_profiles', ['user_id'], unique=False)
    op.create_table('otp_logs',
    sa.Column('otp_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('contact_method', sa.String(length=20), nullable=True),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("contact_method IN ('phone', 'email', 'aadhaar')", name='ck_otp_contact_method'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.create_index('idx_otp_contact', 'otp_logs', ['contact_method', 'contact_value'], unique=False)
    op.create_index('idx_otp_user_id', 'otp_logs', ['user_id'], unique=False)
    op.create_table('property_listings',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('tower_building_name', sa.String(length=255), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=True),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('configuration', sa.String(length=20), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('total_area_sqft', sa.Integer(), nullable=True),
    sa.Column('rentable_area_type', sa.String(length=50), nullable=True),
    sa.Column('furnishing', sa.String(length=20), nullable=True),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('has_fridge', sa.Boolean(), nullable=False),
    sa.Column('has_ac', sa.Boolean(), nullable=False),
    sa.Column('has_fans', sa.Boolean(), nullable=False),
    sa.Column('has_washing_machine', sa.Boolean(), nullable=False),
    sa.Column('has_tv', sa.Boolean(), nullable=False),
    sa.Column('has_gas_connection', sa.Boolean(), nullable=False),
    sa.Column('parking_type', sa.String(length=20), nullable=True),
    sa.Column('wc_type', sa.String(length=20), nullable=True),
    sa.Column('total_bathrooms', sa.Integer(), nullable=True),
    sa.Column('water_supply_type', sa.String(length=50), nullable=True),
    sa.Column('water_supply_hours', sa.String(length=100), nullable=True),
    sa.Column('property_age_years', sa.Integer(), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=False),
    sa.Column('non_veg_allowed', sa.Boolean(), nullable=False),
    sa.Column('drinking_allowed', sa.Boolean(), nullable=False),
    sa.Column('partying_allowed', sa.Boolean(), nullable=False),
    sa.Column('guests_allowed', sa.Boolean(), nullable=False),
    sa.Column('suitable_for', sa.Text(), nullable=True),
    sa.Column('open_for_gender', sa.String(length=20), nullable=True),
    sa.Column('open_for_occupation', sa.Text(), nullable=True),
    sa.Column('cook_available', sa.Boolean(), nullable=False),
    sa.Column('maid_available', sa.Boolean(), nullable=False),
    sa.Column('distance_to_metro', sa.Integer(), nullable=True),
    sa.Column('distance_to_train', sa.Integer(), nullable=True),
    sa.Column('distance_to_bus_stop', sa.Integer(), nullable=True),
    sa.Column('distance_to_airport', sa.Integer(), nullable=True),
    sa.Column('distance_to_gym', sa.Integer(), nullable=True),
    sa.Column('distance_to_hospital', sa.Integer(), nullable=True),
    sa.Column('distance_to_grocery', sa.Integer(), nullable=True),
    sa.Column('distance_to_mall', sa.Integer(), nullable=True),
    sa.Column('distance_to_movie_theatre', sa.Integer(), nullable=True),
    sa.Column('current_flatmates_count', sa.Integer(), nullable=False),
    sa.Column('flatmates_info', sa.Text(), nullable=True),
    sa.Column('rent_monthly', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('brokerage_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('maintenance_monthly', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('electricity_charges', sa.String(length=100), nullable=True),
    sa.Column('water_charges', sa.String(length=100), nullable=True),
    sa.Column('wifi_charges', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('other_charges_onetime', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('other_charges_monthly', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('charges_notes', sa.Text(), nullable=True),
    sa.Column('possession_date', sa.Date(), nullable=False),
    sa.Column('minimum_lease_months', sa.Integer(), nullable=False),
    sa.Column('other_highlights', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('contact_requests_count', sa.Integer(), nullable=False),
    sa.Column('photos_verified', sa.Boolean(), nullable=False),
    sa.Column('photos_verified_at', sa.DateTime(), nullable=True),
    sa.Column('photos_verified_by', sa.UUID(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', sa.Date(), nullable=True),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("property_type IN ('apartment', 'house', 'pg', 'villa', 'independent_floor')", name='ck_listing_property_type'),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photos_verified_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index('idx_listing_city', 'property_listings', ['city'], unique=False)
    op.create_index('idx_listing_host_id', 'property_listings', ['host_id'], unique=False)
    op.create_index('idx_listing_possession', 'property_listings', ['possession_date'], unique=False)
    op.create_index('idx_listing_premium', 'property_listings', ['is_premium', 'is_featured'], unique=False)
    op.create_index('idx_listing_rent', 'property_listings', ['rent_monthly'], unique=False)
    op.create_index('idx_listing_status', 'property_listings', ['status'], unique=False)
    op.create_table('tenant_priorities',
    sa.Column('priority_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('budget_priority', sa.Integer(), nullable=True),
    sa.Column('occupancy_priority', sa.Integer(), nullable=True),
    sa.Column('location_priority', sa.Integer(), nullable=True),
    sa.Column('possession_priority', sa.Integer(), nullable=True),
    sa.Column('gender_priority', sa.Integer(), nullable=True),
    sa.Column('property_type_priority', sa.Integer(), nullable=True),
    sa.Column('lifestyle_priority', sa.Integer(), nullable=True),
    sa.Column('furnishing_priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('priority_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tenant_profiles',
    sa.Column('tenant_profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occupation_type', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('educational_institution', sa.String(length=255), nullable=True),
    sa.Column('smoking', sa.String(length=10), nullable=True),
    sa.Column('drinking', sa.String(length=10), nullable=True),
    sa.Column('food_preference', sa.String(length=20), nullable=True),
    sa.Column('lifestyle_notes', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hobbies', sa.Text(), nullable=True),
    sa.Column('languages_spoken', sa.Text(), nullable=True),
    sa.Column('profile_completeness', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("drinking IN ('yes', 'no', 'occasionally')", name='ck_tenant_drinking'),
    sa.CheckConstraint("food_preference IN ('veg', 'non_veg', 'both', 'vegan', 'eggetarian')", name='ck_tenant_food'),
    sa.CheckConstraint("occupation_type IN ('working_professional', 'student', 'self_employed', 'actor', 'actress', 'freelancer', 'other')", name='ck_tenant_occupation'),
    sa.CheckConstraint("smoking IN ('yes', 'no', 'occasionally')", name='ck_tenant_smoking'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_tenant_profile_user_id', 'tenant_profiles', ['user_id'], unique=False)
    op.create_table('tenant_requirements',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('budget_max', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('preferred_localities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occupancy', sa.String(length=20), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('furnishing', sa.String(length=20), nullable=True),
    sa.Column('possession_date', sa.Date(), nullable=False),
    sa.Column('lease_duration_months', sa.Integer(), nullable=True),
    sa.Column('gender_preference', sa.String(length=20), nullable=True),
    sa.Column('flatmate_occupation_preference', sa.Text(), nullable=True),
    sa.Column('want_non_smoker', sa.Boolean(), nullable=False),
    sa.Column('want_non_drinker', sa.Boolean(), nullable=False),
    sa.Column('want_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('want_non_party', sa.Boolean(), nullable=False),
    sa.Column('other_preferences', sa.Text(), nullable=True),
    sa.Column('contact_visibility', sa.String(length=50), server_default='verified_hosts_only', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_expires_at', sa.Date(), nullable=True),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'paused', 'expired', 'fulfilled', 'deleted')", name='ck_tenant_req_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_index('idx_tenant_req_budget', 'tenant_requirements', ['budget_min', 'budget_max'], unique=False)
    op.create_index('idx_tenant_req_possession', 'tenant_requirements', ['possession_date'], unique=False)
    op.create_index('idx_tenant_req_premium', 'tenant_requirements', ['is_premium', 'expires_at'], unique=False)
    op.create_index('idx_tenant_req_status', 'tenant_requirements', ['status'], unique=False)
    op.create_index('idx_tenant_req_user_id', 'tenant_requirements', ['user_id'], unique=False)
    op.create_table('user_verifications',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=False),
    sa.Column('face_id_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('aadhaar_verified_at', sa.DateTime(), nullable=True),
    sa.Column('face_id_verified_at', sa.DateTime(), nullable=True),
    sa.Column('aadhaar_last_4_digits', sa.String(length=4), nullable=True),
    sa.Column('aadhaar_verification_reference', sa.String(length=100), nullable=True),
    sa.Column('face_id_reference', sa.String(length=100), nullable=True),
    sa.Column('face_verification_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_fully_verified', sa.Boolean(), sa.Computed('phone_verified AND email_verified AND aadhaar_verified AND face_id_verified', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verification_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_verifications_status', 'user_verifications', ['is_fully_verified'], unique=False)
    op.create_index('idx_verifications_user_id', 'user_verifications', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('compatibility_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('match_status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('contact_shared', sa.Boolean(), nullable=False),
    sa.Column('contact_shared_at', sa.DateTime(), nullable=True),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.Column('visit_scheduled', sa.Boolean(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('visit_status', sa.String(length=20), nullable=True),
    sa.Column('deal_closed', sa.Boolean(), nullable=False),
    sa.Column('deal_closed_at', sa.DateTime(), nullable=True),
    sa.Column('deal_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.Column('unmatched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.listing_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['tenant_requirements.requirement_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('tenant_id', 'host_id', 'listing_id', name='uq_match_unique')
    )
    op.create_index('idx_match_host', 'matches', ['host_id'], unique=False)
    op.create_index('idx_match_listing', 'matches', ['listing_id'], unique=False)
    op.create_index('idx_match_requirement', 'matches', ['requirement_id'], unique=False)
    op.create_index('idx_match_status', 'matches', ['match_status'], unique=False)
    op.create_index('idx_match_tenant', 'matches', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_for', sa.String(length=50), nullable=True),
    sa.Column('related_listing_id', sa.UUID(), nullable=True),
    sa.Column('related_requirement_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("payment_for IN ('tenant_listing', 'host_listing', 'premium_listing', 'tenant_subscription', 'host_subscription', 'verification_badge', 'featured_listing', 'boost')", name='ck_payment_for'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed', 'refunded', 'cancelled')", name='ck_payment_status'),
    sa.ForeignKeyConstraint(['related_listing_id'], ['property_listings.listing_id'], ),
    sa.ForeignKeyConstraint(['related_requirement_id'], ['tenant_requirements.requirement_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index('idx_payment_gateway_txn', 'payments', ['gateway_transaction_id'], unique=False)
    op.create_index('idx_payment_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payment_user', 'payments', ['user_id'], unique=False)
    op.create_table('property_photos',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('photo_type', sa.String(length=50), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("photo_type IN ('room', 'kitchen', 'bathroom', 'hall', 'balcony', 'building_exterior', 'street_view', 'other')", name='ck_photo_type'),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index('idx_property_photos_listing', 'property_photos', ['listing_id', 'sequence_order'], unique=False)
    op.create_table('saved_items',
    sa.Column('saved_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('saved_listing_id', sa.UUID(), nullable=True),
    sa.Column('saved_requirement_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(saved_listing_id IS NOT NULL AND saved_requirement_id IS NULL) OR (saved_listing_id IS NULL AND saved_requirement_id IS NOT NULL)', name='ck_saved_target'),
    sa.ForeignKeyConstraint(['saved_listing_id'], ['property_listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_requirement_id'], ['tenant_requirements.requirement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('saved_id'),
    sa.UniqueConstraint('user_id', 'saved_listing_id', name='uq_saved_listing'),
    sa.UniqueConstraint('user_id', 'saved_requirement_id', name='uq_saved_requirement')
    )
    op.create_index('idx_saved_user', 'saved_items', ['user_id'], unique=False)
    op.create_table('swipe_actions',
    sa.Column('swipe_id', sa.UUID(), nullable=False),
    sa.Column('swiper_id', sa.UUID(), nullable=False),
    sa.Column('swiper_type', sa.String(length=10), nullable=True),
    sa.Column('swiped_listing_id', sa.UUID(), nullable=True),
    sa.Column('swiped_requirement_id', sa.UUID(), nullable=True),
    sa.Column('swiped_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('compatibility_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('like', 'dislike', 'super_like', 'skip')", name='ck_swipe_action'),
    sa.CheckConstraint('(swiped_listing_id IS NOT NULL AND swiped_requirement_id IS NULL) OR (swiped_listing_id IS NULL AND swiped_requirement_id IS NOT NULL)', name='ck_swipe_target'),
    sa.ForeignKeyConstraint(['swiped_listing_id'], ['property_listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['swiped_requirement_id'], ['tenant_requirements.requirement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['swiped_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['swiper_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('swipe_id'),
    sa.UniqueConstraint('swiper_id', 'swiped_listing_id', name='uq_swipe_listing'),
    sa.UniqueConstraint('swiper_id', 'swiped_requirement_id', name='uq_swipe_requirement')
    )
    op.create_index('idx_swipe_listing', 'swipe_actions', ['swiped_listing_id'], unique=False)
    op.create_index('idx_swipe_requirement', 'swipe_actions', ['swiped_requirement_id'], unique=False)
    op.create_index('idx_swipe_swiper', 'swipe_actions', ['swiper_id'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index('idx_conv_host', 'conversations', ['host_id'], unique=False)
    op.create_index('idx_conv_tenant', 'conversations', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_user_id', sa.UUID(), nullable=True),
    sa.Column('related_listing_id', sa.UUID(), nullable=True),
    sa.Column('related_requirement_id', sa.UUID(), nullable=True),
    sa.Column('related_match_id', sa.UUID(), nullable=True),
    sa.Column('sent_via_app', sa.Boolean(), nullable=False),
    sa.Column('sent_via_email', sa.Boolean(), nullable=False),
    sa.Column('sent_via_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('sent_via_sms', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("notification_type IN ('like_received', 'match_made', 'message_received', 'visit_scheduled', 'visit_reminder', 'listing_expiring', 'requirement_expiring', 'payment_reminder', 'verification_pending', 'new_matching_listing', 'new_matching_requirement', 'system_announcement')", name='ck_notif_type'),
    sa.ForeignKeyConstraint(['related_listing_id'], ['property_listings.listing_id'], ),
    sa.ForeignKeyConstraint(['related_match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['related_requirement_id'], ['tenant_requirements.requirement_id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_notif_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_notif_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('idx_notif_user', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('ratings',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('rated_user_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('rating_value', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('review_title', sa.String(length=255), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('communication_rating', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('accuracy_rating', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('responsiveness_rating', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_reported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating_value >= 1.0 AND rating_value <= 5.0', name='ck_rating_value'),
    sa.ForeignKeyConstraint(['listing_id'], ['property_listings.listing_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rated_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_id'),
    sa.UniqueConstraint('rater_id', 'rated_user_id', 'match_id', name='uq_rating_unique')
    )
    op.create_index('idx_rating_match', 'ratings', ['match_id'], unique=False)
    op.create_index('idx_rating_rated_user', 'ratings', ['rated_user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discount_applied', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('final_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'expired', 'cancelled', 'paused')", name='ck_subscription_status'),
    sa.CheckConstraint("subscription_type IN ('tenant_basic', 'tenant_premium', 'host_basic', 'host_premium')", name='ck_subscription_type'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index('idx_subscription_status', 'subscriptions', ['status', 'expires_at'], unique=False)
    op.create_index('idx_subscription_user', 'subscriptions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=20), server_default='text', nullable=False),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("message_type IN ('text', 'image', 'document', 'system', 'visit_request', 'visit_confirmation')", name='ck_msg_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_msg_conversation', 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_index('idx_msg_sender', 'messages', ['sender_id'], unique=False)
    op.create_table('whatsapp_notifications',
    sa.Column('whatsapp_notif_id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message_template', sa.String(length=100), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'sent', 'delivered', 'read', 'failed')", name='ck_whatsapp_status'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('whatsapp_notif_id')
    )
    op.create_index('idx_whatsapp_status', 'whatsapp_notifications', ['status'], unique=False)
    op.create_index('idx_whatsapp_user', 'whatsapp_notifications', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=True),
    sa.Column('reported_listing_id', sa.UUID(), nullable=True),
    sa.Column('reported_requirement_id', sa.UUID(), nullable=True),
    sa.Column('reported_message_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reported_listing_id'], ['property_listings.listing_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_message_id'], ['messages.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_requirement_id'], ['tenant_requirements.requirement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_report_reporter', 'reports', ['reporter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_report_reporter', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_whatsapp_user', table_name='whatsapp_notifications')
    op.drop_index('idx_whatsapp_status', table_name='whatsapp_notifications')
    op.drop_table('whatsapp_notifications')
    op.drop_index('idx_msg_sender', table_name='messages')
    op.drop_index('idx_msg_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_subscription_user', table_name='subscriptions')
    op.drop_index('idx_subscription_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_rating_rated_user', table_name='ratings')
    op.drop_index('idx_rating_match', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('idx_notif_user', table_name='notifications')
    op.drop_index('idx_notif_type', table_name='notifications')
    op.drop_index('idx_notif_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_conv_tenant', table_name='conversations')
    op.drop_index('idx_conv_host', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_swipe_swiper', table_name='swipe_actions')
    op.drop_index('idx_swipe_requirement', table_name='swipe_actions')
    op.drop_index('idx_swipe_listing', table_name='swipe_actions')
    op.drop_table('swipe_actions')
    op.drop_index('idx_saved_user', table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_index('idx_property_photos_listing', table_name='property_photos')
    op.drop_table('property_photos')
    op.drop_index('idx_payment_user', table_name='payments')
    op.drop_index('idx_payment_status', table_name='payments')
    op.drop_index('idx_payment_gateway_txn', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_match_tenant', table_name='matches')
    op.drop_index('idx_match_status', table_name='matches')
    op.drop_index('idx_match_requirement', table_name='matches')
    op.drop_index('idx_match_listing', table_name='matches')
    op.drop_index('idx_match_host', table_name='matches')
    op.drop_table('matches')
    op.drop_index('idx_verifications_user_id', table_name='user_verifications')
    op.drop_index('idx_verifications_status', table_name='user_verifications')
    op.drop_table('user_verifications')
    op.drop_index('idx_tenant_req_user_id', table_name='tenant_requirements')
    op.drop_index('idx_tenant_req_status', table_name='tenant_requirements')
    op.drop_index('idx_tenant_req_premium', table_name='tenant_requirements')
    op.drop_index('idx_tenant_req_possession', table_name='tenant_requirements')
    op.drop_index('idx_tenant_req_budget', table_name='tenant_requirements')
    op.drop_table('tenant_requirements')
    op.drop_index('idx_tenant_profile_user_id', table_name='tenant_profiles')
    op.drop_table('tenant_profiles')
    op.drop_table('tenant_priorities')
    op.drop_index('idx_listing_status', table_name='property_listings')
    op.drop_index('idx_listing_rent', table_name='property_listings')
    op.drop_index('idx_listing_premium', table_name='property_listings')
    op.drop_index('idx_listing_possession', table_name='property_listings')
    op.drop_index('idx_listing_host_id', table_name='property_listings')
    op.drop_index('idx_listing_city', table_name='property_listings')
    op.drop_table('property_listings')
    op.drop_index('idx_otp_user_id', table_name='otp_logs')
    op.drop_index('idx_otp_contact', table_name='otp_logs')
    op.drop_table('otp_logs')
    op.drop_index('idx_host_profile_user_id', table_name='host_profiles')
    op.drop_index('idx_host_profile_category', table_name='host_profiles')
    op.drop_table('host_profiles')
    op.drop_table('host_preferences')
    op.drop_index('idx_users_user_type', table_name='users')
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_account_status', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
